---
name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
  pull_request:

permissions:
  checks: write
  contents: write
  packages: read

jobs:
  zizmor:
    name: 🌈 zizmor

    permissions:
      security-events: write
      checks: write
      contents: write
      packages: read

    # yamllint disable-line rule:line-length
    uses: zizmorcore/workflow/.github/workflows/reusable-zizmor.yml@3bb5e95068d0f44b6d2f3f7e91379bed1d2f96a8

  gather_status_zizmor:
    name: Gather Status for zizmor
    runs-on: ubuntu-latest
    needs: zizmor
    if: always()

    steps:
      - name: Gather Status
        uses: invisirisk/pse-action@latest
        with:
          api_url: https://app.invisirisk.com
          app_token: ${{ secrets.IR_API_KEY_ZIZMOR }}
          send_job_status: "true"
          debug: "true"
